### ISSUE TITLE
where can I download anno/att of OTB-100?

### ISSUE THREAD

**Issue by Jiangfeng-Xiong** [HakaseH/CF_benchmark_results#2]
[The official toolkit of OTB](http://cvlab.hanyang.ac.kr/tracker_benchmark)  tracker_benchmark_v1.0.zip only contains annotation for OTB-2013, where do you get these att data in you repository codes 
 [OTB/anno/OTB100](https://github.com/HakaseH/CF_benchmark_results/tree/master/codes/OTB/anno/OTB100/att) , and besides, it has more than 100 files?
Thank you!

**Comment by Escheee** [comment]
My mistake, I merge annotations for UAV123 into OTB100 fold in the last commit.
You can find all annotations in [tracker_benchmark_v1.1](https://goo.gl/U44dEf) which is the modified tracker benchmark contain in UAV123 project.

**Comment by Jiangfeng-Xiong** [comment]
Okay，Thanks

**Comment by Jiangfeng-Xiong** [comment]
I download  tracker_benchmark_v1.1， however，it only has annotations for UAV123. @HakaseH
